# text_to_image_by_ps333.py

import streamlit as st
import requests
from io import BytesIO

# Page Config
st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

# Optional custom AWM favicon
st.markdown("""
<head>
    <link rel="icon" href="https://i.ibb.co/9rJB6WW/awm-icon.png" type="image/png">
</head>
""", unsafe_allow_html=True)

# Mobile styling
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }
    input, textarea {
        font-size: 18px !important;
    }
    button {
        font-size: 18px !important;
    }
</style>
""", unsafe_allow_html=True)

# App Title
st.title("🔫 Text 2 Img by PS333")

# Prompt Input
prompt = st.text_input("Enter your prompt", placeholder="E.g. A tiger meditating on a mountain peak")

# Style Selection
style = st.selectbox("Select Image Style", ["Realistic", "Cartoon", "Fantasy", "Cyberpunk", "Anime", "Photorealistic"])

# Generate Button
if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):

            formatted_prompt = f"{style} style {prompt}".replace(" ", "%20")
            image_url = f"https://image.pollinations.ai/prompt/{formatted_prompt}"

            # Display image
            st.image(image_url, use_column_width=True, caption="Generated by AI")
            st.success("✅ Image created!")

            # Download Image
            try:
                img_response = requests.get(image_url)
                if img_response.status_code == 200:
                    img_bytes = BytesIO(img_response.content)
                    st.download_button(
                        label="⬇️ Download Image",
                        data=img_bytes,
                        file_name="generated_image.png",
                        mime="image/png"
                    )
            except Exception as e:
                st.error("Failed to load image for download.")

            # Direct image link
            st.markdown(f"🔗 [Open Full Image]({image_url})")

# Footer
st.markdown("---")
st.markdown("🔧 Built by **PS333** | Powered by **Pollinations AI**")