# text2imgPS333.py

import streamlit as st
import requests

# Page config
st.set_page_config(
    page_title="Text 2 Img by PS333",
    page_icon="🧠",
    layout="centered"
)

# Background image (custom)
st.markdown(
    f"""
    <style>
    .stApp::before {{
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-image: url("https://i.ibb.co/6Jfmhkh7/34e1a10894d62bce16ac68a92e98931e.jpg");
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.15;  /* 👈 Thoda halka effect */
        z-index: -1;
    }}
    .block-container {{
        padding-top: 2rem;
        padding-bottom: 2rem;
        position: relative;
        z-index: 1;
    }}
    input, textarea {{
        font-size: 18px !important;
    }}
    button {{
        font-size: 18px !important;
    }}
    </style>
    """,
    unsafe_allow_html=True
)

# Logo image and title
st.image("https://i.ibb.co/5Wp2sxxn/1000319964-removebg-preview.png", width=250)
st.title("🔥 PS333 Image Generator 🔥")

# Prompt Input
prompt = st.text_input("Enter your prompt", placeholder="E.g. A tiger meditating on a mountain peak")

# Style Selection
style = st.selectbox("Select Image Style", ["Realistic", "Cartoon", "Fantasy", "Cyberpunk", "Anime", "Photorealistic"])

# Generate Button
if st.button("✨ Generate Image"):
    if prompt.strip() == "":
        st.warning("Please enter a valid prompt.")
    else:
        with st.spinner("⏳ Generating your image..."):

            formatted_prompt = f"{style} style {prompt}".replace(" ", "%20")
            image_url = f"https://image.pollinations.ai/prompt/{formatted_prompt}"

            st.image(image_url, use_column_width=True, caption="Generated by AI")
            st.success("✅ Image created!")
            st.markdown(f"🔗 [Open Full Image]({image_url})")

            # Download button
            st.download_button(
                label="📥 Download Image",
                data=requests.get(image_url).content,
                file_name="generated_image.png",
                mime="image/png"
            )

# Footer
st.markdown("---")
st.markdown(
    '🔧 Made with ❤️ by [**PS333**](https://instagram.com/prabhveersingh01) | 🔥 Powered by **PS333 AI Studio**'
)
